### PR TITLE
creating map 2016 results

### PR DESCRIPTION
**Pull request by SandraLeriche**
@cielly-belly since you're also working on creating a map using Chloropleth I'd love to have your help and maybe work on this together later this week. 

I'm not sure if you can spot what I'm doing wrong here when setting up the chloropleth details.
Trying to plot the results of the 2016 election by counties on an actual USA map using 'CountyFips' and 'Party'
Do not merge to master for now since this code isn't giving the expected results.

Thank you for your help,
Sandra

### CODE REVIEW

**Comment by cielly-belly** [comment]
I'll definitely have a look and let you know if there's something I can help with!

**Review by cielly-belly — CHANGES_REQUESTED** [review]
Good work, Sandra! I have just added on the CountyFips to be 5 digits so that it gets captured correctly by plotly

**Comment by SandraLeriche** [comment]
@cielly-belly Thanks for your help. 
The reason why it was not plotting is because each county had the count of votes for all parties (ie. 5 for DEM, 7 for GOP, 10 for CST etc.).

I've transformed the data to show only the party with the majority of votes for each county and it is now plotting.
Would be interesting to compare it to the 2020 poll map. Even though we have county level vs state level, if we compare the too maps we can still see how the tendency may have changed in 4 years. 

This is now ready to be merged into the master branch.

Thanks

**Comment by cielly-belly** [comment]
That looks good! Glad you were able to figure out how to make it work!

**Pull request merged**
