### PR TITLE
Test_ys - Forecast.ipynb

### PR DESCRIPTION
**Pull request by youshinee**
Jun can you please see whether i need to improve my visualisation. Thanks.

### CODE REVIEW

**Comment by junjun9** [comment]
@youshinee The forecast looks great. From my point of view, the graph is slightly empty. I am wondering if it would be better to increase the width of the bars?

**Comment by youshinee** [comment]
Ok jun i will do that and as soon as i finish updating the graphs i will let you know to merge the pull request. Thanks.

**Comment by youshinee** [comment]
Jun i have already updated the graph, can you please review to merge the file. Thanks a lot.

**Comment by junjun9** [comment]
@youshinee This is great! Well done. Do you want to save the graphs to the visualisation folder before I merge the branch to the master?

**Comment by youshinee** [comment]
@junjun9 Thanks.
Oh yes, well how should i save the visualisation. Can you help me out please.

**Comment by SandraLeriche** [comment]
@youshinee you can use "plt.savefig("../visualisations/file_name.jpg", dpi = 200)" before plt.show()
however that will only work if your branch was branched out when the visualisations folder already existed.

**Comment by youshinee** [comment]
@SandraLeriche  but what if the file is already merged in master and then i write the code to save the graphs, will it work in this case..?! Because my branch does not have the visualisation folder.

**Comment by youshinee** [comment]
ok i have already saved the graphs @junjun9  you can merge now.

**Comment by junjun9** [comment]
@SandraLeriche Thanks for sharing! @youshinee I saw your graphs in visualisations folder on your branch. I will merge your branch to the master now.

**Comment by youshinee** [comment]
Yes i just save them, thanks Jun

**Comment by junjun9** [comment]
@SandraLeriche I have met a conflict before I merge this branch to master. I deleted '.DS_Store' but the conflict hasn't been resolved. Do you know how to resolve this?

**Comment by youshinee** [comment]
Can you please try to merge it again jun.

**Comment by junjun9** [comment]
@youshinee It's still showing "This branch has conflicts that must be resolved". Would you able to merge from your side?

**Review by junjun9 — APPROVED** [review]

**Comment by youshinee** [comment]
Thanks jun, its merged now, great.

**Pull request merged**
