### PR TITLE
Adding visualisation for voting tendencies by education

### PR DESCRIPTION
**Pull request by SandraLeriche**
Hi Team,

**Please do not merge**, still working on poverty_level, please have a look at the visualisation created so far in the visualisations folder.
Any comments/feedback would be appreciated.

Thank you,

### CODE REVIEW

**Comment by youshinee** [comment]
That is cool, you have able to merge both graphs.

**Review by cielly-belly — CHANGES_REQUESTED** [review]
maybe you could make the dots smaller for aesthetics

**Comment by SandraLeriche** [comment]
@cielly-belly Thanks for your feedback, I've reduced the size of the dots. 

A chart on poverty level has also been added

Please review and merge to master.

Thanks,

**Review by cielly-belly — APPROVED** [review]
Thanks for updating the dot size! Looks much better.
Also, a very interesting insight that you added on. I wonder if this same statistic will play a part in the upcoming elections

**Review by caitlincurrey — APPROVED** [review]

**Pull request merged**
