### PR TITLE
Forecast.ipynb

### PR DESCRIPTION
**Pull request by youshinee**
The bar graph shows the forecast for the top states who are in favour of Trump winning the election.
Can you please give some feedback, thanks.

I will add the forecast for Biden as well.

### CODE REVIEW

**Comment by caitlincurrey** [comment]
Looks good, can we confirm what NE-3 is? I did some Googling and it looks like it might be Nebraska's 3rd Congressional District. But I am not sure why it would be displayed separately like this. I saw the raw data and it includes a handful of these "States" that aren't actual States. Nebraska is showing in your Top10 so doesn't make sense to include it twice at a district level. Can you filter it out?

**Comment by caitlincurrey** [comment]
To clarify you'd want to filter out "ME-1", "ME-2", "NE-1", "NE-2", "NE-3"

**Comment by caitlincurrey** [comment]
Also I wasn't able to "read_csv" using the code 

# Get the working directory
os.getcwd()
# Get input data from directory, load the file for the Presidential state toplines
mypath = ('us-elections/data/clean_data/2020/presidential_state_toplines_2020.csv')
df = pd.read_csv(os.path.join(os.getcwd(), mypath), encoding='utf-8')
df.shape

But I was able to read it simply using:
df = pd.read_csv("../data/clean_data/2020/presidential_state_toplines_2020.csv", encoding = 'utf-8')

Does this work for you if you replace those 3 lines with this single line? I copied this from Sandra's code and it worked well for me, would be good to have them consistent as they will all end up in the same code notebook eventually.

**Review by caitlincurrey — COMMENTED** [review]
Few points:
- Filter the following from state before plotting: NE-1, NE-2, NE-3, ME-1, ME-2
- Can we replace first 3 lines of code with:
`df = pd.read_csv("../data/clean_data/2020/presidential_state_toplines_2020.csv", encoding = 'utf-8')`

**Comment by youshinee** [comment]
Thanks caitlin for the feedback. Yeah it makes more sense to avoid the duplicates districts. I will drop the state and update the reading part for the csv file.

**Pull request merged**
